workflows:
    build-firebase:
        name: Build and publish to Firebase
        max_build_duration: 120
        instance_type: mac_mini_m1
        triggering:
            events:
                - push
            branch_patterns:
                - pattern: 'release_AntonBabko'
                  include: true
        environment:
            groups:
                - firebase_credentials
            ios_signing:
                distribution_type: development
                bundle_identifier: ua.edu.ukma.apple-env.babko.CatsAndModules_AntonBabko
            vars:
                BUNDLE_ID: "ua.edu.ukma.apple-env.babko.CatsAndModules_AntonBabko"
                XCODE_WORKSPACE: "CatsAndModules_AntonBabko.xcworkspace"
                XCODE_SCHEME: "CatsAndModules_AntonBabko"
            xcode: latest
        scripts:
            - name: Set up provisioning profiles settings on Xcode project
              script: xcode-project use-profiles
            - name: Build ipa for distribution
              script: |
                  xcode-project build-ipa \
                      --workspace "$CM_BUILD_DIR/$XCODE_WORKSPACE" \
                      --scheme "$XCODE_SCHEME"
        artifacts:
            - build/ios/ipa/CatsAndModules_AntonBabko.ipa
        publishing:
            firebase:
                firebase_service_account: $FIREBASE_SERVICE_ACCOUNT
                ios:
                    app_id: 1:212332764592:ios:e0269f81075f2c15048a75
                    groups:
                        - devgroup
