workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m1
        script: echo "Hello world"
    triggering:
        events:
            - push
        branch_patterns:
            - pattern: release_AntonBabko
                include: true
        
